import java.io.File;
import java.io.FileNotFoundException;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author scott
 */
public class MorseCodePanel extends javax.swing.JPanel {
	MorseCodeConverter Morse = new MorseCodeConverter();
	MorseCodeTree Tree = new MorseCodeTree();

	private File input;

    /**
     * Creates new form Assgn5
     */
    public MorseCodePanel() {
        initComponents();
        String Print=Tree.PrintTree();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMorse = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaString = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        ConvertFile = new javax.swing.JButton();
        ConvertString = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Morse Code(' '  seperator for letters '/' seperator for words)");

        jTextAreaMorse.setColumns(20);
        jTextAreaMorse.setRows(5);
        jScrollPane1.setViewportView(jTextAreaMorse);

        jTextAreaString.setColumns(20);
        jTextAreaString.setRows(5);
        jScrollPane2.setViewportView(jTextAreaString);
        jTextAreaString.setEnabled(false);
        
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("English Translation");

        ConvertFile.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ConvertFile.setText("Convert File");
        ConvertFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	ConvertFileActionPerformed(evt);
            }
        });

        ConvertString.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ConvertString.setText("Convert String");
        ConvertString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	ConvertStringActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ConvertFile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ConvertString)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Exit)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConvertFile)
                    .addComponent(ConvertString)
                    .addComponent(Exit))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>
    private void ConvertStringActionPerformed(java.awt.event.ActionEvent evt) {
    
    	
    		String Translated="";
    		try{
    		Translated=Morse.convertToEnglish(jTextAreaMorse.getText());
    		jTextAreaString.setText(Translated);
    		}
    		catch (NoCodeFoundException e1){
				JOptionPane.showMessageDialog(null, e1.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        
    		}         
  }
    private void ConvertFileActionPerformed(java.awt.event.ActionEvent evt) {
    	JFileChooser chooser = new JFileChooser();
		int status;
		chooser.setDialogTitle("Select Document File");
		status = chooser.showOpenDialog(null);
		if(status == JFileChooser.APPROVE_OPTION)
		{
			File inFile = chooser.getSelectedFile();
				input=inFile;
				try {
					//Docs.ReadFromFile(inFile);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}  
		}
		String Translated="";
		try {
			Translated=Morse.convertToEnglish(input);
		} catch (FileNotFoundException e1) {
			JOptionPane.showMessageDialog(null, e1.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
			e1.printStackTrace();
		}
		jTextAreaString.setText(Translated);
        
    }
    
    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {
    	System.exit(0);
    }
    // Variables declaration - do not modify
    private javax.swing.JButton ConvertFile;
    private javax.swing.JButton ConvertString;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaMorse;
    private javax.swing.JTextArea jTextAreaString;
    // End of variables declaration
}
